### ISSUE TITLE
Syntax error on Windows 10 device

### ISSUE THREAD

**Issue by aximobile** [pouchdb-community/pouchdb-authentication#162]
Hello,

We are implementing a cordova project and use Pouchdb as the local database and IBM Cloudant as the remote database.

We upgraded  Pouchdb from 5.4.5 to 6.3.4 and pouchdb-authentication from 0.4.3 to 0.5.5.

On Android and IOS, everything works fine with the new versions.
But on Windows, we receive the following error when we invoke a **login** on our remote Cloudant database: 

`Error while logging in:  Error: SyntaxError
   at xhRequest (ms-appx-web://be.axi.specto.ontw/www/lib/pouchdb-authentication/dist/pouchdb.authentication.js:1506:5)
   at ajax$1 (ms-appx-web://be.axi.specto.ontw/www/lib/pouchdb-authentication/dist/pouchdb.authentication.js:1611:5)
   at ajaxCore (ms-appx-web://be.axi.specto.ontw/www/lib/pouchdb-authentication/dist/pouchdb.authentication.js:2145:3)
   at ajax (ms-appx-web://be.axi.specto.ontw/www/lib/pouchdb-authentication/dist/pouchdb.authentication.js:2202:3)
   at Anonymous function (ms-appx-web://be.axi.specto.ontw/www/lib/pouchdb-authentication/dist/pouchdb.authentication.js:3752:3)
   at Anonymous function (ms-appx-web://be.axi.specto.ontw/www/lib/pouchdb-authentication/dist/pouchdb.authentication.js:72:9)
   at Promise (native code)
   at Anonymous function (ms-appx-web://be.axi.specto.ontw/www/lib/pouchdb-authentication/dist/pouchdb.authentication.js:60:5)
   at Anonymous function (ms-appx-web://be.axi.specto.ontw/www/lib/pouchdb-authentication/dist/pou
console-via-logger.js (173,15)
`

We get this error after invoking following method:

`                remoteDb.login(username, password).then(function (user) {
                    resolve(user);
                }, function (err) {
                    $log.error('Error while logging in: ', err);
                    if (err.name === 'unauthorized') {
                        onError($filter('translate')('i18n_login.loginfail'));
                    } else {
                        onError($filter('translate')('i18n_login.could_not_login'));
                    }
                });`

Everything worked fine with the previous pouchdb-authentication version.
We tested this on a windows 10 device.

Any help would be appreciated.

Kind regards

Wouter

**Comment by ptitjes** [comment]
Looking at the code, it seems the browser is complaining about your URL. Could you tell us that URL ?

**Comment by ptitjes** [comment]
Closing this issue as it seems to be stale. Please do reopen a ticket if you still experience this.
